export const Icons = {
  instructor1: require("./ins1.png"),
  instructor2: require("./inst2.png"),
  instructor3: require("./ins3.png"),
  instructor4: require("./inst4.png"),
  live1: require("./live1.png"),
  live2: require("./live2.png"),
  live3: require("./live3.png"),
  live4: require("./live4.png"),
  star: require("./Star.png"),
  course: require("./course.png"),
  profile: require("./profile.png"),
  home: require("./home.png"),
  store: require("./store.png"),
  formula: require("./formula.png"),
  bookLover: require("./bookLover.png"),
  communication: require("./communication.jpeg"),
  circle: require("./circle.png"),
  brain: require("./brain.png"),
  angiosperms: require("./angiosperms.png"),
  parokaryotic: require("./parokaryotic.png"),

};
