const ScreenNames = {
  STARTUP: 'StartUp',
  HOME: 'Home',
  VIDEO: 'Video',
  BOTTOM_TAB: 'BottomTab',
  STORE: 'Store',
  PROFILE: 'Profile',
  LOGIN: 'Login',
  VERIFY_OTP: 'Verification',
  CHAPTER_DETAILS: 'ChapterDetails',
  SUBJECT_DETAILS: 'SubjectDetails',
  DETAILS: 'Details',
  NOTIFICATIONS: 'Notifications',
  LIVE_CLASS_DETAILS: 'LiveClassDetails',
  LIVE_CLASSES: 'LiveClassesScreen',
  TOPIC_DETAILS: 'TopicDetails',
  MY_COURSE: 'MyCourse',
  VIDEO_PLAYBACK: 'VideoPlayback',
  USER_PROFILE: 'UserProfile',
  EDIT_PROFILE: 'EditProfile',
};
export default ScreenNames;
